# Site settings
title: Shed Hollaway II
#twitter_username: @
name: Shed Hollaway II

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/shedh2
 - title: DataCamp
   url: https://datacamp.com/profile/shedh2
 - title: LinkedIn
   url: https://www.linkedin.com/in/shedhollawayii

#Any buzzword skills you want to include
skills:
 - R
 - SAS
 - Tableau
 - Python
 - Spark
 - Java
 - Cassandra
 - SQL

#Work experience is required
roles:
 - title: Senior Manager
   start: 2011
   end: 2016
   employer: Oracle
   #description: 
 - title: Director of Academic Computing
   start: 2009
   end: 2011
   employer: Edward Waters College
   #description: 
 - title: Application Engineer
   start: 2007
   end: 2008
   employer: Citigroup
   #description: 

#Education is required
education:
 - level: Master of Science (M.S.)
   date: 2008
   subject: Information Systems
   school: University of Phoenix

#This section is optional (as is the image link below)
#coursera:
 #  profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
  # courses:
  #- title: Functional Programming Principles in Scala
   #   link: https://www.coursera.org/course/progfun
    #  optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
     # date: September 16, 2013


#List of interesting Github repo/projects to include - optional
github:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
